### ISSUE TITLE
Cleanup after WYSIWYD Year 2 demo

### ISSUE THREAD

**Issue by pattacini** [robotology-playground/react-control#10]
- [x] Update `README.md` _consistently_.
- [x] Remove as many `v0.x` tags as possible :wink:.
- [x] Move the repository to [**`robotology`**](https://github.com/robotology) (I'll do that).
- AOB?

@matejhof

**Comment by matejhof** [comment]
@pattacini please Czech the readme and then you can move to robotology!

**Comment by pattacini** [comment]
Seems fine to me, thanks!
I'll proceed with moving the repo very soon.
Stay tuned.

**Comment by pattacini** [comment]
Done, closing.

@matejhof @towardthesea
