### ISSUE TITLE
Investigate conditions yielding all the Ipopt return codes

### ISSUE THREAD

**Issue by pattacini** [robotology-playground/react-control#11]
Start off a campaign to inquiry all the conditions where Ipopt fails to solve the task, i.e. terminates with exit codes different from `successful`.

**Comment by towardthesea** [comment]
This also happens even when the `desired position` is close to the `current position` in the `real robot`.
```[INFO][reactController] received new relative x_d: -0.050  0.000  0.000
[INFO][reactCtrlThread] got new target: x_0: -0.240 -0.264  0.068
[INFO][reactCtrlThread]                 x_d: -0.290 -0.264  0.068
[WARNING][reactCtrlThread] Ipopt cpu time was higher than the rate of the thread!
[WARNING][reactCtrlThread] Ipopt cpu time was higher than the rate of the thread!
[WARNING][reactCtrlThread] Ipopt cpu time was higher than the rate of the thread!
[WARNING][reactCtrlThread] Ipopt cpu time was higher than the rate of the thread!
[WARNING][reactCtrlThread] Ipopt cpu time was higher than the rate of the thread!
[WARNING][reactCtrlThread] Ipopt cpu time was higher than the rate of the thread!
[WARNING][reactCtrlThread] Ipopt cpu time was higher than the rate of the thread!
[WARNING][reactCtrlThread] Ipopt cpu time was higher than the rate of the thread!
[WARNING][reactCtrlThread] Ipopt cpu time was higher than the rate of the thread!
[WARNING][reactCtrlThread] Ipopt cpu time was higher than the rate of the thread!
[WARNING][reactCtrlThread] Ipopt cpu time was higher than the rate of the thread!
[WARNING][reactCtrlThread] Ipopt cpu time was higher than the rate of the thread!
[WARNING][reactCtrlThread] Ipopt cpu time was higher than the rate of the thread!
[WARNING][reactCtrlThread] Ipopt cpu time was higher than the rate of the thread!
[WARNING][reactCtrlThread] Ipopt cpu time was higher than the rate of the thread!
[WARNING][reactCtrlThread] Ipopt cpu time was higher than the rate of the thread!
[WARNING][reactCtrlThread] Ipopt cpu time was higher than the rate of the thread!
[WARNING][reactCtrlThread] Ipopt cpu time was higher than the rate of the thread!
[WARNING][reactCtrlThread] Ipopt cpu time was higher than the rate of the thread!
[WARNING][reactCtrlThread] Ipopt cpu time was higher than the rate of the thread!
[WARNING][reactCtrlThread] Ipopt cpu time was higher than the rate of the thread!
[WARNING][reactCtrlThread] Ipopt cpu time was higher than the rate of the thread!
```
Working conditions are set as following:
```
[INFO][reactController] rctCTrlThread working at 20 ms.
[INFO][reactController] part to use is: left_arm
[INFO][reactController] disableTorso flag set to off.
[INFO][reactController] tactileCollisionPoints flag set to on.
[INFO][reactController] visualCollisionPoints flag set to on.
[INFO][reactController] gazeControl flag set to off.
[INFO][reactController] stiff interaction flag set to off.
[INFO][reactController] globalTol to reach target set to 0.01 m.
[INFO][reactController] referenceGen to use is: none
[INFO][reactController] particleThread period (if referenceGen == uniformParticle)  10 ms.
[INFO][reactController] trajSpeed (if referenceGen == uniformParticle) set to 0.1 s.
[INFO][reactController] vMax (max joint vel) set to 20 [deg/s].
[INFO][reactController] controlMode to use is: positionDirect
[INFO][reactController] ipopt: tol set to 0.001 m.
[INFO][reactController] hittingConstraints flag set to on.
[INFO][reactController] orientationControl flag set to on.
[INFO][reactController] additionalControlPoints flag set to off.
[INFO][reactController] ipOptMemory flag set to off.
[INFO][reactController] ipOptFilter flag set to off.
[INFO][reactController] ipopt: boundSmoothnessFlag flag set to off.
[INFO][reactController] visualizeTargetInSim flag set to off.
[INFO][reactController] visualizeParticleInSim flag set to off.
```

But in `simulation`, it stops when I set the `globalTol` as `0.005`.

**Comment by matejhof** [comment]
`Ipopt cpu time was higher than the rate of the thread!` is very common and usually not critical. 

"It stops in simulation" - does that mean it reached the target?

**Comment by towardthesea** [comment]
@matejhof 
I meant in `simulation` when I set it like that I can receive in the terminal some information about the `reached` situation like this:
```[INFO][reactController] received new x_d: -0.400 -0.100 -0.050
[INFO][reactCtrlThread] got new target: x_0: -0.238 -0.352  0.150
[INFO][reactCtrlThread]                 x_d: -0.400 -0.100 -0.050
[WARNING][reactCtrlThread] Ipopt cpu time was higher than the rate of the thread!
[WARNING][reactCtrlThread] Ipopt cpu time was higher than the rate of the thread!
[WARNING][reactCtrlThread] Ipopt cpu time was higher than the rate of the thread!
                  ( I myself remove similar lines)
[WARNING][reactCtrlThread] Ipopt cpu time was higher than the rate of the thread!
[WARNING][reactCtrlThread] Ipopt cpu time was higher than the rate of the thread!
[DEBUG][reactCtrlThread] norm(x_t-x_d) 0.00409117	globalTol 0.005
[INFO][reactCtrlThread] finished.
```
But in `real robot` it didn't happen again, at least with `globalTol` as `0.005` or `0.01`

**Comment by alecive** [comment]
If you increase the `globalTol`, it makes sense that the cpu time is lower. Higher tolerance means that there are more allowed final positions for the solver to stop at, and more allowed positions means that it is easier for the solver to find one of them.

Even though increasing `globalTol` seems to solve the issue, it may actually hide a bigger problem in terms of code efficiency. If I were in you, I would  do some serious debugging to see where the culprit is, and try to optimize the code instead. Moreover, a tolerance of `5mm` seems too big to me. @pattacini what is the tolerance you use in the Cartesian Controller?

 > Ipopt cpu time was higher than the rate of the thread! is very common and usually not critical.

@matejhof true, but only because we solve the problem every 10 ms. If we were to solve the problem once, the solution would not be found properly - at least, it would not be within the `globalTol`. This error means that the solver is continuously failing.

@towardthesea Btw, there should be no difference between the real robot and the simulation.

**Comment by matejhof** [comment]
i think you may be confusing `globalTol` and the ipopt `tol`. The latter is internal for ipopt. The former is the global one that will just stop the thread and consider it solved - will not query ipopt anymore. This should still be your heritage @alecive I think. For the ipopt `tol`, I was sticking with @pattacini 's settings - this is black magic.

**Comment by alecive** [comment]
Right. I was looking at the code but is now too different from what I remember. Anyway, if I recall correctly, `globalTol` was used to check if the end effector reached the final desired position, whereas `tol` sets the internal tolerance for IPOPT at each step.

If this is the case, then it does not make sense that `globalTol` param affects the IPOPT cpu time, unless the desired position is very strange - at the limits of the operational space for example - and very difficult to reach precisely. 

@towardthesea does this happen **always** or only with some configurations?

**Comment by pattacini** [comment]
@alecive `5mm` is generally ok to stop the movement and consider the action done; however, it could be a parameter.

What @matejhof says about `globalTol` and `tol` is correct; nonetheless, also @alecive is correct in pointing that `globalTol` shouldn't affect `Ipopt` solving time.

**Comment by matejhof** [comment]
yes, I think that from the way the software is designed, `globalTol` does not affect anything what concerns `Ipopt`. I suspect that the differences come from comparing the real robot and the simulator - this is running on different machines (I suppose). Even if not, running the simulator puts burden on the processor etc. - so it is easy to imagine differences in the comp. power available to `Ipopt`. Plus the actual motor control is different too.

**Comment by pattacini** [comment]
Stale issue, closing.
