### ISSUE TITLE
Remove dependency from motionPlan

### ISSUE THREAD

**Issue by towardthesea** [robotology-playground/react-control#18]
Currently, the [integration-plan](https://github.com/robotology/react-control/tree/integration-planner) branch is compiled with `motionPlan` dependency to work with input from [reaching-planner](https://github.com/robotology-playground/reaching-planner). 

It is necessary to provide option to compile it without that dependency as before!

**Comment by pattacini** [comment]
This is because react-controller can also run without receiving information from the planner, as per the original design.

**Comment by matejhof** [comment]
@towardthesea can you handle this?
I will be able to join back hands-on from April onwards...

**Comment by towardthesea** [comment]
Hi,
I plan to solve the issue by this way:
1. In **CMakeLists.txt** of ` reactController` module, add this following part after `find_package(reaching-with-avoidance)`
```
if(NOT (reaching-with-avoidance_FOUND))
	add_definitions(-DWITH_PLAN=FALSE)
	message(WARNING "I will build without motionPlan")
else()
	add_definitions(-DWITH_PLAN=TRUE)
	message(WARNING "I will build with motionPlan")
endif()
```

2. In all `source` and `header` files, which uses `motionPlan`,  add
```
#if WITH_PLAN
        <current motionPlan variables/funtions>
#endif
```

If there is a better solution, please show me!

**Comment by pattacini** [comment]
Hi @towardthesea 

I'd better do within `CMake`:
```cmake
if(reaching-with-avoidance_FOUND)
  add_definitions(-DWITH_PLAN)
else()
  message(WARNING "motionPlan not found, proceeding without")
endif()
```
and in `C++`:
```cpp
#ifdef WITH_PLAN
// ...
#endif
```

**Comment by pattacini** [comment]
I've got a concern with lots of `#ifdef` within the code...

**Comment by pattacini** [comment]
After a quick discussion with @towardthesea it came out that it's much better to factor out such a dependency, being the controller a mere server receiving data from the network.

Thus, the next step in mid-term will be to remove the dependency outright.

**Comment by towardthesea** [comment]
The [PR](https://github.com/robotology/react-control/pull/19) is opened to solve this!

**Comment by towardthesea** [comment]
I close this then!
