### ISSUE TITLE
Possible bug in converting from radians to degrees

### ISSUE THREAD

**Issue by alecive** [robotology-playground/react-control#22]
As we're working toward integrating the avoidance into our controller, we have found the following potential issue:

 * in [AvoidanceHandlerTactile::getVLIM](https://github.com/robotology/react-control/blob/devel/modules/reactController/src/avoidanceHandler.cpp#L265), you compute the new joint velocity limits given the obstacle.
 * These limits are in radians per second.
 * Then, you provide the new limits to the NLP, but the function you call [here](https://github.com/robotology/react-control/blob/devel/modules/reactController/src/reactCtrlThread.cpp#L998) accepts only degrees per seconds.

Is this a bug?

**Comment by matejhof** [comment]
Hmmm, let's have a look!

1. My convention has been that:

- everything in `reactCtrlThread` is in `deg`
- everything in `reactIpOpt` in `rad`

2. I would say that `AvoidanceHandler` should also be in `deg`. 
- the avoiding speed is meant to be in deg/s: https://github.com/robotology/react-control/blob/devel/modules/reactController/src/avoidanceHandler.cpp#L209
- what remains unclear is this line: https://github.com/robotology/react-control/blob/devel/modules/reactController/src/avoidanceHandler.cpp#L237
the `J.transposed()*normal` term. I suspect `J` as coming from `iKin` in `rad`. Then this could be a bug. I never fully understood this J transpose trick that apparently resorts to a dynamic interpretation (forces) according to @pattacini. It is like the Eq. 13 in Flacco et al. ICRA 2012.

**Comment by alecive** [comment]
I think the issue is in the last equation. The usual equation (`x_dot = J q_dot`) considers `q_dot`  in `rad/s`, so I believe the dimensions of the Jacobian itself should be something like `m/rad`.

Which means that in the last equation we're comparing apples with oranges, hence the mismatch afterwards.

**Comment by matejhof** [comment]
This is how I also understand it. Good catch! 
The same problem would then seem to be in @pattacini 's simulation:
https://github.com/robotology/react-control/blob/devel/modules/reactController-sim/main.cpp#L712
https://github.com/robotology/react-control/blob/devel/modules/reactController-sim/main.cpp#L932
https://github.com/robotology/react-control/blob/devel/modules/reactController-sim/main.cpp#L935
Shall we wait for @pattacini to confirm?
Converting to degs could result in the system being much more reponsive / "avoidive" than before...

**Comment by pattacini** [comment]
Guys, unfortunately, I have zero time to deal with this issue. I firmly believe you're skilled enough to sort it out 😉 

The assumption you have to start reasoning with is that any time you handle a Jacobian or you have to do some math, always stick to radians.

Degrees are only used to make humans happy when their limited abilities to visualize rotations kick in.

**Comment by alecive** [comment]
> The assumption you have to start reasoning with is that any time you handle a Jacobian or you have to do some math, always stick to radians.

> Degrees are only used to make humans happy when their limited abilities to visualize rotations kick in.

Exactly, hence the bug. @matejhof any opinion?

**Comment by matejhof** [comment]
I guess bug, yes. How do we proceed? You fix it in your software and here I can assign myself to test and then commit a fix?

**Comment by alecive** [comment]
The fact that our codebase is different means that it should be tested on the iCub as well. Also, since it's only a costant no behaviour would be probably affected (a part from "speed of avoidance"). If you prefer, I can do a PR , though
